### ISSUE TITLE
Adición de las fincas para el Macro lote No.3

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/Hato_Viejo#10]
20210308 Mañana debemos retirar y entregar los planos catastrales de Contraloría al MIVIOT.
__________________
Debemos adicionar las siguientes fincas al PH Originario para crear el macro lote No.3

- [x] Finca 9145 - Villas Campestres

- [x] Finca 15090 - Villas Campestres

- [x] Finca 30228342 - Calle a Villas Campestres
