### ISSUE TITLE
Global - Cancelación y liberación de Fincas del PH Originario

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/Hato_Viejo#214]
Se inicia el tramite para la liberación de las fincas que se están adicionando al PH Originario y que particularmente forman parte de Villas Campestres. 

En primera instancia necesitamos

- [ ] Calculo de la cuota parte de los prestamos a cancelar
- [ ] Pago de la cuota parte
- [ ] Entrega de la minuta de cancelación
- [ ] Registro de la minuta de cancelación y obtención de nuevos certificados de registro publico.
