### ISSUE TITLE
Alarmas para Hato Viejo

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/Hato_Viejo#368]
- [ ] Club Ecuestre: Alarma de incendios 
- [ ] Administración Villas Campestres: Alarma de incendios
- [ ] Area Social Villas Campestres: Alarma de incendios 
- [ ] Casa Club Villas Campestres: Alarma de incendios y alarma de seguridad 
- [ ] Casa Modelo Hato Viejo Village: Alarma de seguridad
- [ ] Casa del Ingeniero: Alarma de seguridad
